apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-collector
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: otel-collector
  template:
    metadata:
      labels:
        app: otel-collector
    spec:
      containers:
      - name: otel-collector
        image: otel/opentelemetry-collector-contrib:0.100.0
        args: ["--config=/etc/otelcol-contrib/config.yml"]
        ports:
        - containerPort: 4317
        - containerPort: 4318
        - containerPort: 8889
        volumeMounts:
        - name: otel-config
          mountPath: /etc/otelcol-contrib/config.yml
          subPath: otel-collector-config.yaml
      volumes:
      - name: otel-config
        configMap:
          name: monitoring-configs
---
apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  namespace: microbooks
spec:
  selector:
    app: otel-collector
  ports:
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
  - name: metrics
    port: 8889
    targetPort: 8889
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:v2.53.0
        args:
          - "--config.file=/etc/prometheus/prometheus.yml"
          - "--web.enable-remote-write-receiver"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus/prometheus.yml
          subPath: prometheus.yml
      volumes:
      - name: prometheus-config
        configMap:
          name: monitoring-configs
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: microbooks
spec:
  selector:
    app: prometheus
  ports:
  - port: 9090
    targetPort: 9090
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.1.0
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_USER
          value: "admin"
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: "admin"
        volumeMounts:
        - name: grafana-provisioning-datasources
          mountPath: /etc/grafana/provisioning/datasources/datasources.yaml
          subPath: datasources.yaml
        - name: grafana-provisioning-dashboards
          mountPath: /etc/grafana/provisioning/dashboards/dashboards.yaml
          subPath: dashboards.yaml
        - name: grafana-dashboards
          mountPath: /var/lib/grafana/dashboards/microservices-dashboard.json
          subPath: microservices-dashboard.json
      volumes:
      - name: grafana-provisioning-datasources
        configMap:
          name: monitoring-configs
      - name: grafana-provisioning-dashboards
        configMap:
          name: monitoring-configs
      - name: grafana-dashboards
        configMap:
          name: monitoring-configs
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: microbooks
spec:
  selector:
    app: grafana
  ports:
  - port: 3005
    targetPort: 3000
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loki
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loki
  template:
    metadata:
      labels:
        app: loki
    spec:
      containers:
      - name: loki
        image: grafana/loki:3.1.0
        args: ["-config.file=/etc/loki/loki-config.yaml"]
        ports:
        - containerPort: 3100
        volumeMounts:
        - name: loki-config
          mountPath: /etc/loki/loki-config.yaml
          subPath: loki-config.yaml
      volumes:
      - name: loki-config
        configMap:
          name: monitoring-configs
---
apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: microbooks
spec:
  selector:
    app: loki
  ports:
  - port: 3100
    targetPort: 3100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: promtail
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: promtail
  template:
    metadata:
      labels:
        app: promtail
    spec:
      serviceAccountName: promtail # Cần quyền để đọc Pod log
      containers:
      - name: promtail
        image: grafana/promtail:3.1.0
        args: ["-config.file=/etc/promtail/promtail-config.yml"]
        volumeMounts:
        - name: promtail-config
          mountPath: /etc/promtail/promtail-config.yml
          subPath: promtail-config.yaml
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: promtail-config
        configMap:
          name: monitoring-configs
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tempo
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tempo
  template:
    metadata:
      labels:
        app: tempo
    spec:
      containers:
      - name: tempo
        image: grafana/tempo:2.5.0
        args: ["-config.file=/etc/tempo/tempo.yaml"]
        ports:
        - containerPort: 3200
        volumeMounts:
        - name: tempo-config
          mountPath: /etc/tempo/tempo.yaml
          subPath: tempo.yaml
      volumes:
      - name: tempo-config
        configMap:
          name: monitoring-configs
---
apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: microbooks
spec:
  selector:
    app: tempo
  ports:
  - port: 3200
    targetPort: 3200
