apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: kietne1211/microbooks-frontend:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 3
        resources:
          limits:
            cpu: "500m"
            memory: "1Gi"
          requests:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: ORDER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: microbooks-config
              key: ORDER_SERVICE_URL
        - name: INVENTORY_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: microbooks-config
              key: INVENTORY_SERVICE_URL
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: microbooks
spec:
  selector:
    app: frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
