apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: microbooks
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
    spec:
      containers:
      - name: inventory-service
        image: kietne1211/microbooks-inventory-service:latest
        ports:
        - containerPort: 3002
        livenessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3002
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: microbooks-secrets
              key: MONGO_URI
        - name: KAFKA_BROKER
          valueFrom:
            configMapKeyRef:
              name: microbooks-config
              key: KAFKA_BROKER
        - name: SERVICE_PORT
          value: "3002"
        - name: OTEL_ENABLED
          value: "true"
        - name: OTEL_SERVICE_NAME
          value: "inventory-service"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: microbooks-config
              key: OTEL_EXPORTER_OTLP_ENDPOINT
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: microbooks
spec:
  selector:
    app: inventory-service
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer
