apiVersion: v1
kind: ConfigMap
metadata:
  name: microbooks-config
  namespace: microbooks
data:
  KAFKA_BROKER: "kafka-service:9092"
  ORDER_SERVICE_URL: "http://order-service:3001"
  INVENTORY_SERVICE_URL: "http://inventory-service:3002"
  ORDER_SERVICE_PORT: "3001"
  INVENTORY_SERVICE_PORT: "3002"
  FRONTEND_PORT: "3000"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
