apiVersion: v1 # Phiên bản API cơ bản của Kubernetes
kind: ConfigMap # Loại tài nguyên dùng để lưu trữ các tham số cấu hình không nhạy cảm
metadata: # Thông tin mô tả
  name: microbooks-config # Tên của ConfigMap để các Pod tham chiếu tới
  namespace: microbooks # Đặt trong không gian tên microbooks
data: # Danh sách các cặp Key-Value chứa dữ liệu cấu hình
  KAFKA_BROKER: "kafka-service:9092" # Địa chỉ kết nối tới cụm Kafka trong nội bộ Cluster
  ORDER_SERVICE_URL: "http://order-service:3001" # URL gọi API của dịch vụ đơn hàng
  INVENTORY_SERVICE_URL: "http://inventory-service:3002" # URL gọi API của dịch vụ kho hàng
  ORDER_SERVICE_PORT: "3001" # Cổng dịch vụ đơn hàng
  INVENTORY_SERVICE_PORT: "3002" # Cổng dịch vụ kho hàng
  FRONTEND_PORT: "3000" # Cổng dịch vụ giao diện
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318" # Địa chỉ nhận dữ liệu OpenTelemetry qua giao thức HTTP
