apiVersion: v1
kind: ResourceQuota
metadata:
  name: microbooks-quota
  namespace: microbooks
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "4Gi"
    limits.cpu: "8"
    limits.memory: "8Gi"
    pods: "50"
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: frontend-pdb
  namespace: microbooks
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: frontend
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: order-service-pdb
  namespace: microbooks
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: order-service
