apiVersion: v1
kind: Secret
metadata:
  name: microbooks-secrets
  namespace: microbooks
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://truongquockiet1211_db_user:1234567890@cnlthd.ijxnmqz.mongodb.net/?appName=CNLTHD"
  JWT_SECRET: "dev-secret-change"
  ADMIN_EMAIL: "admin@microbooks.com"
  ADMIN_PASSWORD: "admin123"
