apiVersion: v1 # Phiên bản API cơ bản
kind: Secret # Loại tài nguyên dùng để lưu trữ các thông tin nhạy cảm (mật khẩu, key)
metadata: 
  name: microbooks-secrets # Tên của Secret để các dịch vụ tham chiếu tới
  namespace: microbooks
type: Opaque # Loại dữ liệu không có cấu hình mặc định (dùng cho dữ liệu bất kỳ)
stringData: # Cho phép ghi trực tiếp chuỗi văn bản (K8s sẽ tự động mã hóa Base64 khi lưu)
  MONGO_URI: "mongodb+srv://truongquockiet1211_db_user:1234567890@cnlthd.ijxnmqz.mongodb.net/?appName=CNLTHD" # Chuỗi kết nối Database MongoDB
  JWT_SECRET: "dev-secret-change" # Khóa bí mật dùng để tạo và xác thực Token JWT
  ADMIN_EMAIL: "admin@microbooks.com" # Email tài khoản quản trị hệ thống
  ADMIN_PASSWORD: "admin123" # Mật khẩu tài khoản quản trị hệ thống
