apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/secrets.yaml
  - config/configmap.yaml
  - infrastructure/kafka.yaml
  - infrastructure/monitoring.yaml
  - services/order-service.yaml
  - services/inventory-service.yaml
  - services/frontend.yaml
  - ingress.yaml
