apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - config/secrets.yaml
  - config/configmap.yaml
  - config/monitoring-configs.yaml
  - infrastructure/kafka.yaml
  - infrastructure/kafka-ui.yaml
  - infrastructure/promtail-rbac.yaml
  - infrastructure/monitoring.yaml
  - services/order-service.yaml
  - services/inventory-service.yaml
  - services/frontend.yaml
  - config/hpa.yaml
  - config/quotas.yaml
  - ingress.yaml
